Data dataObj;
String objFileName = "pointcloud";
String objFilePath = "scripts";
String objFileType = "obj";

void objMain() {
  objBegin();
  for (int i=0;i<voxel.length;i++) {
    for (int j=0;j<voxel[i].length;j++) {
      for (int k=0;k<voxel[i][j].length;k++) {
        if (voxel[i][j][k].drawMe) {
          dataObj.add("v " + (voxel[i][j][k].p.x) + " " + (voxel[i][j][k].p.y) + " " + (voxel[i][j][k].p.z));
        }
      }
    }
  }
  objEnd();
}



//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

void objBegin() {
  dataObj = new Data();
  dataObj.beginSave();
  //dataObj.add("####");
  //dataObj.add("#");
  //dataObj.add("# OBJ file generated by Meshlab");
  //dataObj.add("#");
  dataObj.add("####");
  //dataObj.add("# Object render_shot1_12.obj");
  dataObj.add("#");
  dataObj.add("# Vertices: "+ countVertices());
  dataObj.add("# Faces: 0");
  dataObj.add("#");
  dataObj.add("####");
}

void objEnd() {
  dataObj.add("# "+ countVertices() +" vertices, 0 vertex normals");
  dataObj.add("");
  dataObj.add("# 0 faces, 0 texture coords");
  dataObj.add("");
  dataObj.add("# End of File");
  dataObj.endSave(objFilePath + "/" + objFileName + "." + objFileType);
}

int countVertices(){
  int counter=0;
  for (int i=0;i<voxel.length;i++) {
    for (int j=0;j<voxel[i].length;j++) {
      for (int k=0;k<voxel[i][j].length;k++) {
        if(voxel[i][j][k].drawMe){
        counter++;
        }
      }
    }
  }
  return counter;
}
